In [71]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
print('libs loaded')

libs loaded


In [19]:
prices = pd.read_csv('datas/price_availability.csv', sep=';');
prices.describe()

listing_id   local_price    min_nights
count  4.748696e+06  4.748696e+06  4.748696e+06
mean   1.523313e+07  1.944215e+02  7.877554e+00
std    9.190721e+06  2.289745e+02  2.407054e+01
min    5.396000e+03  9.000000e+00  1.000000e+00
25%    6.351188e+06  7.900000e+01  2.000000e+00
50%    1.641294e+07  1.440000e+02  3.000000e+00
75%    2.353692e+07  2.400000e+02  4.000000e+00
max    2.885198e+07  1.000300e+04  3.650000e+02

In [113]:
# listings = listings.drop(589);
X = listings.loc[:, ['listing_id', "person_capacity", "bedrooms", "bathrooms"]]
Y = []

In [114]:
for i, row in X.iterrows():
    y = 0
    ID = int(row["listing_id"])
    subset = prices[prices["listing_id"] == ID]
    y = subset["local_price"].mean()
    Y.append(y)

Y = np.asarray(Y)

In [115]:
Y

array([  45.94845361,   44.47368421,   49.        ,  165.        ,
         69.77443609,   80.56363636,   61.10909091,  213.32460733,
        174.02849741,  169.        ,  183.0848329 ,  297.76315789,
        170.        ,   49.95275591,   71.13740458,  160.        ,
        409.54887218,   35.06887755,   62.13533835,  107.37402597,
        358.12121212,  115.        ,  106.71428571,   76.06896552,
        302.        ,   36.58961039,   65.48484848,  153.25      ,
         75.8762089 ,  284.35356201,  219.5037594 ,  113.53383459,
         93.57142857,  151.07915567,  300.        ,  109.96240602,
         59.07772021,  101.37984496,   67.20833333,   60.74093264,
         38.        ,   92.        ,   66.21204188,   79.68041237,
         90.09819121,  170.        ,  115.7544757 ,  283.76115486,
        144.74424552,  347.67015707,  115.        ,  105.        ,
        154.65384615,  380.        ,   44.16569201,  233.69170984,
        147.96623377,  105.        ,  163.47286822,  190.     

In [116]:
X

listing_id  person_capacity  bedrooms  bathrooms
0      28581061                1         1        2.0
1        661961                2         1        1.0
2       1261705                1         1        1.0
3       1318834                3         2        1.0
4       1677091                2         1        1.0
..          ...              ...       ...        ...
995    28335197                2         0        1.0
996    28583013                3         1        1.0
997    28628316                4         1        1.0
998    28792796                6         2        1.5
999    28682896                2         1        1.0

[999 rows x 4 columns]

In [117]:
Y

array([  45.94845361,   44.47368421,   49.        ,  165.        ,
         69.77443609,   80.56363636,   61.10909091,  213.32460733,
        174.02849741,  169.        ,  183.0848329 ,  297.76315789,
        170.        ,   49.95275591,   71.13740458,  160.        ,
        409.54887218,   35.06887755,   62.13533835,  107.37402597,
        358.12121212,  115.        ,  106.71428571,   76.06896552,
        302.        ,   36.58961039,   65.48484848,  153.25      ,
         75.8762089 ,  284.35356201,  219.5037594 ,  113.53383459,
         93.57142857,  151.07915567,  300.        ,  109.96240602,
         59.07772021,  101.37984496,   67.20833333,   60.74093264,
         38.        ,   92.        ,   66.21204188,   79.68041237,
         90.09819121,  170.        ,  115.7544757 ,  283.76115486,
        144.74424552,  347.67015707,  115.        ,  105.        ,
        154.65384615,  380.        ,   44.16569201,  233.69170984,
        147.96623377,  105.        ,  163.47286822,  190.     

In [129]:
Y_train, X_train, Y_test, X_test =train_test_split(X, Y, test_size=0.30, random_state=42)
X_train.shape, X_test.shape

((300, 4), (300,))

In [125]:
X_train

listing_id  person_capacity  bedrooms  bathrooms
453    14992207                2         1        1.0
794    24564156                2         1        1.0
209     3452604                2         0        1.0
309     8243908                1         1        1.0
741    23233753                5         2        1.0
..          ...              ...       ...        ...
314     8525469                8         3        2.5
404    12976143                7         3        2.0
7       5662637                2         1        1.0
155     2158913                2         0        1.0
810    24766158                9         4        3.0

[300 rows x 4 columns]

In [128]:
X_test

array([  79.81038961,  125.        ,   95.45333333,   29.        ,
         82.5883905 ,  123.63829787,  360.        ,  130.        ,
        450.        ,  164.845953  ,   68.35142119,  294.18181818,
         68.08247423,   51.01595745,  170.30548303,   80.24479167,
         73.78249337,  195.        ,  375.0268714 ,  834.96124031,
        850.65633075,   89.        ,  650.        ,   63.38219895,
         83.        ,  190.        ,  202.23514212,   96.6056701 ,
        108.95026178,   50.        ,   28.31937173,  195.        ,
         93.70234987,  474.14258189,  450.        ,  517.0984456 ,
         83.37730871,  395.        ,   79.        ,  129.17493473,
        135.11227154,   51.52785146,  117.22572178,  260.        ,
        618.        ,   42.        ,  180.        ,  160.        ,
        179.67315175,   40.0025641 ,   80.984375  ,  116.09947644,
        429.28645833,   76.06896552,  219.5037594 ,  459.71391076,
        183.0848329 ,  204.39276486,  161.5503876 ,  131.     

In [131]:
Y_train.shape

(699, 4)

prix = intercept_ + (person_capacity * 36 ) + ( beds * -26) + (bedrooms *27) + (bathrooms *95)